/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FavoritesDropdown: typeof import('./src/components/ui/FavoritesDropdown.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LogiModalWindow: typeof import('./src/components/ui/LogiModalWindow.vue')['default']
    LoginModalWindow: typeof import('./src/components/ui/LoginModalWindow.vue')['default']
    LoginPopup: typeof import('./src/components/LoginPopup.vue')['default']
    MainFooter: typeof import('./src/components/MainFooter.vue')['default']
    MainNavbar: typeof import('./src/components/MainNavbar.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PopupModalWindow: typeof import('./src/components/ui/PopupModalWindow.vue')['default']
    RegisterPopup: typeof import('./src/components/RegisterPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/ui/SearchBar.vue')['default']
    SmallWeatherItem: typeof import('./src/components/SmallWeatherItem.vue')['default']
    SmallWeatherWidget: typeof import('./src/components/SmallWeatherWidget.vue')['default']
    TempComponent: typeof import('./src/components/TempComponent.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WeatherLine: typeof import('./src/components/WeatherLine.vue')['default']
    WeatherMainItem: typeof import('./src/components/WeatherMainItem.vue')['default']
    WeatherWidget: typeof import('./src/components/WeatherWidget.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
